name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  TZ: Europe/Istanbul

jobs:
  php-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_mysql, intl, zip, gd, bcmath
          coverage: none

      - name: Cache composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ runner.os }}-${{ hashFiles('composer.lock') }}
          restore-keys: composer-${{ runner.os }}-

      - name: Install deps
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Prepare .env
        run: cp .env.example .env && php artisan key:generate

      - name: Lint (Pint)
        run: |
          if [ -f vendor/bin/pint ]; then vendor/bin/pint --test; else echo "skip pint"; fi

      - name: Static Analysis (PHPStan)
        run: |
          if [ -f vendor/bin/phpstan ]; then vendor/bin/phpstan analyse --no-progress; else echo "skip phpstan"; fi

      - name: Tests (PHPUnit)
        run: |
          if [ -f vendor/bin/phpunit ]; then vendor/bin/phpunit --testdox; else echo "skip phpunit"; fi

  docker:
    runs-on: ubuntu-latest
    needs: php-tests
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push (runtime)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/php/Dockerfile
          target: runtime
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:runtime
            ghcr.io/${{ github.repository }}:runtime-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build & Push (worker)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/php/Dockerfile
          target: worker
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:worker
            ghcr.io/${{ github.repository }}:worker-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build & Push (scheduler)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/php/Dockerfile
          target: scheduler
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:scheduler
            ghcr.io/${{ github.repository }}:scheduler-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
